language: erlang
otp_release:
  #- 20.0 # cowlib 1.0.0 has errors
  - 19.3
before_script:
  - rebar get-deps
script: rebar compile ct suites=cloudi_service_filesystem || ( cat logs/raw.log logs/ct_run*/cloudi.log && exit 1 )
after_script:
  - rebar clean
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
